**1. Create a 3x3x3 array with random values.**

In [1]:
import numpy as np
x = np.random.random((3,3,3)) 
print(x)

[[[0.26716662 0.73284042 0.64872356]
  [0.19240703 0.36072404 0.63114916]
  [0.64639194 0.2989908  0.42441688]]

 [[0.40066411 0.09678476 0.48634954]
  [0.38826416 0.35425612 0.00248597]
  [0.81059018 0.37058632 0.17740697]]

 [[0.91529685 0.32365315 0.70483342]
  [0.08100761 0.67138337 0.12484436]
  [0.43435711 0.42994889 0.9649731 ]]]


**2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.**

In [3]:
import numpy as np
x = np.diag([1, 2, 3, 4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


**3. Create a 8x8 matrix and fill it with a checkboard pattern.**

In [4]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**4. Normalize a 5x5 random matrix.**

In [5]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.5372556  0.11883635 0.59321506 0.75157844 0.41475075]
 [0.50398924 0.3495892  0.67369479 0.62620978 0.20953506]
 [0.47198563 0.47691606 0.7989697  0.0142296  0.75703544]
 [0.68333947 0.2105633  0.10834732 0.16631669 0.85498794]
 [0.6001062  0.56116566 0.32020857 0.15293511 0.9464257 ]]
After normalization:
[[0.56106864 0.11221539 0.62109835 0.7909804  0.42965332]
 [0.52538264 0.3597522  0.70743183 0.65649296 0.20951113]
 [0.49105122 0.49634027 0.84181869 0.         0.79683432]
 [0.71777802 0.21061416 0.10096344 0.16314925 0.90191145]
 [0.62849073 0.58671781 0.32823455 0.14879434 1.        ]]


**5. How to find common values between two arrays?**

In [6]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


**6. How to get the dates of yesterday, today and tomorrow?**

In [10]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yesterday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


**7. Consider two random array A and B, check if they are equal.**

In [11]:
import numpy as np
x = np.random.randint(0,2,6)
print("A:")
print(x)
y = np.random.randint(0,2,6)
print("B:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

A:
[0 1 0 1 0 0]
B:
[0 0 1 1 0 0]
Test above two arrays are equal or not!
False


**8. Create random vector of size 10 and replace the maximum value by 0.**

In [9]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[1.21500090e-02 3.84093142e-01 2.65145519e-01 6.40541950e-01
 1.50856904e-01 6.23890743e-01 4.79893221e-01 5.63779547e-04
 4.96854050e-01 4.19089797e-01]
Maximum value replaced by 0:
[1.21500090e-02 3.84093142e-01 2.65145519e-01 0.00000000e+00
 1.50856904e-01 6.23890743e-01 4.79893221e-01 5.63779547e-04
 4.96854050e-01 4.19089797e-01]


**9. How to print all the values of an array.**

**10. Subtract the mean of each row of a matrix.**

In [18]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.33804271 0.59950227 0.23367484 0.42773153 0.36827659 0.27933791
  0.1959157  0.70188021 0.03555143 0.79111397]
 [0.00128707 0.38791853 0.09406127 0.07326725 0.69828319 0.29757311
  0.53211318 0.86388746 0.61572411 0.44385312]
 [0.44374876 0.0614096  0.71472358 0.38901062 0.35388786 0.96839275
  0.65035327 0.04217474 0.47731902 0.62500876]
 [0.21432522 0.92617716 0.09466588 0.91200936 0.30232408 0.151866
  0.86764031 0.6500742  0.13972351 0.35823219]
 [0.67637197 0.65922721 0.68626454 0.32943833 0.89652897 0.57642042
  0.65075253 0.61292723 0.78988846 0.80375966]]

Subtract the mean of each row of the said matrix:

[[-0.05906     0.20239955 -0.16342788  0.03062881 -0.02882612 -0.11776481
  -0.20118702  0.30477749 -0.36155128  0.39401125]
 [-0.39950976 -0.0128783  -0.30673556 -0.32752958  0.29748636 -0.10322372
   0.13131635  0.46309063  0.21492728  0.04305629]
 [-0.02885413 -0.41119329  0.24212068 -0.08359228 -0.11871504  0.49578985
   0.17775038 -0.43042816  0.004

**11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?**

In [20]:
Z = np.ones(10)

I = np.random.randint(0,len(Z),20)

Z += np.bincount(I, minlength=len(Z))

print(Z)

np.add.at(Z, I, 1)

print(Z)

[3. 3. 1. 6. 3. 2. 1. 3. 2. 6.]
[ 5.  5.  1. 11.  5.  3.  1.  5.  3. 11.]


**12. How to get the diagonal of a dot product?**

In [25]:
A = np.random.uniform(0,1,(5,5))

B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

np.sum(A * B.T, axis=1)

np.einsum("ij,ji->i", A, B)

array([0.77030252, 1.18819766, 1.7048417 , 0.58671437, 0.78773056])

**13. How to find the most frequent value in an array?**

In [22]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[8 8 8 4 5 3 8 5 0 4 3 3 5 8 6 5 2 1 4 3 4 8 1 8 0 4 8 6 7 2 0 6 1 3 4 7 1
 6 2 1]
Most frequent value in the above array:
8


**14. How to get the n largest values of an array.**

In [23]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


**15. How to create a record array from a regular array?**

In [24]:
import numpy as np
arra1 = np.array([("Prerak Shah", 88.5, 90),
                 ("Dipen Shah", 87, 99),
             ("Niket Shah", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Prerak Shah' '88.5' '90']
 ['Dipen Shah' '87' '99']
 ['Niket Shah' '85.5' '91']]

Record array;
[(b'Prerak Shah', 88.5, 90) (b'Dipen Shah', 87. , 99)
 (b'Niket Shah', 85.5, 91)]
